# Generated by Django 4.1.2 on 2022-11-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover',
            name='first_enc_date',
            field=models.DateField(default=None),
        ),
    ]
