# Generated by Django 4.1.2 on 2022-11-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0005_alter_discover_first_enc_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discover',
            name='first_enc_date',
        ),
    ]
