# Generated by Django 4.1.2 on 2022-11-18 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0006_remove_discover_first_enc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover',
            name='first_enc_date',
            field=models.DateField(default=datetime.date(2022, 11, 18)),
        ),
    ]
