# Generated by Django 4.1.2 on 2022-11-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0010_alter_discover_first_enc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discover',
            name='first_enc_date',
            field=models.DateField(default='1900-01-01 00:00:00.000'),
        ),
    ]
