# Generated by Django 4.1.2 on 2022-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0015_alter_discover_first_enc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='total_death',
            field=models.IntegerField(default=200000),
        ),
        migrations.AddField(
            model_name='record',
            name='total_patients',
            field=models.IntegerField(default=200000),
        ),
        migrations.AddField(
            model_name='users',
            name='salary',
            field=models.IntegerField(default=500000),
        ),
    ]
