# Generated by Django 4.1.2 on 2022-11-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0016_record_total_death_record_total_patients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discover',
            name='id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='id',
        ),
        migrations.AlterField(
            model_name='discover',
            name='disease_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sqlapp.disease'),
        ),
        migrations.AlterField(
            model_name='record',
            name='disease_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sqlapp.disease'),
        ),
    ]
