# Generated by Django 4.1.2 on 2022-11-18 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0017_remove_discover_id_remove_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discover',
            name='first_enc_date',
            field=models.DateField(default=datetime.date(2022, 11, 19)),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pathogen',
            field=models.CharField(max_length=100),
        ),
    ]
